build:
  image: php:$$PHP_VERSION
  commands:
    # Install composer and dependencies
    - apt-get update && apt-get install -y --no-install-recommends git zlib1g-dev ca-certificates
    - docker-php-ext-install zip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

    # Install php-cs-fixer
    - composer global require fabpot/php-cs-fixer

    # Run the tests
    - cd $$DIR
    - composer install
    - vendor/bin/phpunit
    - test -d src && ~/.composer/vendor/bin/php-cs-fixer fix --dry-run -v --diff src
matrix:
  PHP_VERSION:
    - 5.6
  DIR:
    - wp-content/themes/dh-intranet
    - wp-content/plugins/dh-intranet
